[package]
edition = "2021"
name = "o1vm-stdlib"
version = "0.1.0"
license = "MIT/Apache-2.0"

[dependencies]
ark-ff = { version = "0.4.2" }

[[bin]]
name = "fibonacci"

[[bin]]
name = "field_addition"

[[bin]]
name = "no_action"

[profile.release]
lto = true
panic="abort"
